module.exports = {
  test: {
    username: process.env.DB_USERNAME || '',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || '',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.DB_PORT, 10),
    dialect: 'mysql',
    logging: false,
    pool: {
      max: 30,
      min: 0,
      idle: 20000,
      acquire: 40000,
      evict: 20000,
    },
  },
  development: {
    username: process.env.DB_USERNAME || '',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || '',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.DB_PORT, 10),
    dialect: 'mysql',
    logging: false,
    pool: {
      max: 30,
      min: 0,
      idle: 20000,
      acquire: 40000,
      evict: 20000,
    },
  },
  production: {
    username: process.env.DB_USERNAME || '',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || '',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.DB_PORT, 10),
    dialect: 'mysql',
    logging: false,
    pool: {
      max: 30,
      min: 0,
      idle: 20000,
      acquire: 40000,
      evict: 20000,
    },
  },
};
